In [19]:
import numpy as np
import pandas as pd
import xlsxwriter

In [20]:
data_dyn1 = pd.read_csv("achived/cro_dyn_ex1.csv", index_col=0)
data_dyn2 = pd.read_csv("achived/cro_dyn_ex2.csv", index_col=0)
data_dyn3 = pd.read_csv("achived/cro_dyn_ex3.csv", index_col=0)
data_dyn = pd.concat([data_dyn1, data_dyn2, data_dyn3])
data_dyn

           substrates  function           best           mean           std
0              Sphere  4DE_0123   6.417234e-89   4.454341e-87  6.320932e-87
1              Sphere   3DE_012  1.753935e-103  6.052107e-100  1.325319e-99
2              Sphere   3DE_013   1.655130e-28   1.123190e-26  1.275384e-26
3              Sphere   3DE_023   1.401458e-98   3.506745e-96  8.014556e-96
4              Sphere   3DE_123   1.108716e-99   1.571663e-96  2.427052e-96
..                ...       ...            ...            ...           ...
55  ExpandedShafferF6    2DE_23   3.472502e-01   3.472514e-01  1.049783e-06
56  ExpandedShafferF6     1DE_0   7.179500e-01   7.238480e-01  4.721618e-03
57  ExpandedShafferF6     1DE_1   7.367952e-01   7.406137e-01  1.748291e-03
58  ExpandedShafferF6     1DE_2   3.472502e-01   3.504774e-01  9.631573e-03
59  ExpandedShafferF6     1DE_3   3.495076e-01   3.770391e-01  9.196830e-03

[210 rows x 5 columns]

In [21]:
data_nodyn1 = pd.read_csv("achived/cro_nodyn_ex1.csv", index_col=0)
data_nodyn2 = pd.read_csv("achived/cro_nodyn_ex2.csv", index_col=0)
data_nodyn = pd.concat([data_nodyn1, data_nodyn2])
data_nodyn

           substrates  function          best          mean           std
0              Sphere  4DE_0123  1.188793e-46  7.375575e-45  1.342383e-44
1              Sphere   3DE_012  1.654836e-47  8.670413e-46  1.279931e-45
2              Sphere   3DE_013  3.079961e-15  1.091211e-14  8.667399e-15
3              Sphere   3DE_023  5.803276e-58  6.598474e-56  6.834479e-56
4              Sphere   3DE_123  3.160874e-55  1.782458e-54  1.625402e-54
..                ...       ...           ...           ...           ...
55  ExpandedShafferF6    2DE_23  3.472503e-01  3.472510e-01  7.342239e-07
56  ExpandedShafferF6     1DE_0  7.139224e-01  7.272219e-01  7.065721e-03
57  ExpandedShafferF6     1DE_1  7.389673e-01  7.407961e-01  9.709511e-04
58  ExpandedShafferF6     1DE_2  3.472502e-01  3.472524e-01  5.936165e-06
59  ExpandedShafferF6     1DE_3  3.475179e-01  3.649678e-01  1.517767e-02

[225 rows x 5 columns]

In [22]:
data_classic1 = pd.read_csv("achived/cro_classic_ex1.csv", index_col=0)
data_classic2 = pd.read_csv("achived/cro_classic_ex2.csv", index_col=0)
data_classic3 = pd.read_csv("achived/cro_classic_ex3.csv", index_col=0)
data_classic = pd.concat([data_classic1, data_classic2, data_classic3])
data_classic

           substrates  function          best          mean           std
0              Sphere  4DE_0123  1.278898e-46  2.085574e-45  1.986097e-45
1              Sphere   3DE_012  1.424058e-46  1.315050e-45  1.128144e-45
2              Sphere   3DE_013  2.096419e-15  1.063808e-14  8.265785e-15
3              Sphere   3DE_023  1.672646e-56  3.983555e-55  7.048073e-55
4              Sphere   3DE_123  6.283591e-55  3.015754e-53  4.951948e-53
..                ...       ...           ...           ...           ...
4   ExpandedShafferF6    2DE_23  3.472502e-01  3.472510e-01  7.482591e-07
5   ExpandedShafferF6     1DE_0  7.120668e-01  7.224325e-01  6.981967e-03
6   ExpandedShafferF6     1DE_1  7.388207e-01  7.407143e-01  9.300793e-04
7   ExpandedShafferF6     1DE_2  3.472502e-01  3.536746e-01  1.284872e-02
8   ExpandedShafferF6     1DE_3  3.473780e-01  3.713301e-01  1.311920e-02

[210 rows x 5 columns]

In [23]:
data_dyn_grouped = data_dyn.groupby(data_dyn["substrates"])
data_nodyn_grouped = data_nodyn.groupby(data_nodyn["substrates"])
data_classic_grouped = data_classic.groupby(data_classic["substrates"])

In [24]:
with pd.ExcelWriter("CRO_SL_python.xlsx", engine="xlsxwriter") as writer:
    dyn_format = writer.book.add_format({'bold': True, 'font_color': 'black', "bg_color": "#9dc3e6", 'left':1, 'right':1, 'bottom':1, 'num_format':'0.00E+00'})
    nodyn_format = writer.book.add_format({'bold': True, 'font_color': 'black', "bg_color": "#f8cbad", 'left':1, 'right':1, 'bottom':1, 'num_format':'0.00E+00'})
    classic_format = writer.book.add_format({'bold': True, 'font_color': 'black', "bg_color": "#ffd966", 'left':1, 'right':1, 'bottom':1, 'num_format':'0.00E+00'})
    average_format = writer.book.add_format({'bold': True, 'font_color': 'black', "bg_color": "#AAAAAA", 'left':1, 'right':1, 'bottom':1, 'num_format':'0.00E+00'})

    for i in pd.unique(data_dyn["substrates"]):
        table_dyn = data_dyn_grouped.get_group(i)
        table_dyn.pop("substrates")

        table_nodyn = data_nodyn_grouped.get_group(i)
        table_nodyn.pop("substrates")
        table_nodyn.pop("function")

        table_classic = data_classic_grouped.get_group(i)
        table_classic.pop("substrates")
        table_classic.pop("function")

        s_name = f"{i[:15]}(30); eval=3e5"
        
        table_dyn.to_excel(writer, sheet_name=s_name, index=False, startrow=1)
        table_nodyn.to_excel(writer, sheet_name=s_name, index=False, startrow=1, startcol=4)
        table_classic.to_excel(writer, sheet_name=s_name, index=False, startrow=1, startcol=7)

        writer.sheets[s_name].merge_range("B1:D1", "CRO_SL-Dyn")
        writer.sheets[s_name].merge_range("E1:G1", "CRO_SL")
        writer.sheets[s_name].merge_range("H1:J1", "CRO_SL-Classic")

        for col in "BCDEFGHIJ":
            writer.sheets[s_name].write_formula(f"{col}18:{col}18", "{" + f"=(AVERAGE({col}3:{col}17))" + "}", average_format)
        
        writer.sheets[s_name].conditional_format("B1:D17", {'type': 'cell', 'criteria': '!=', 'value': "Dummy",'format': dyn_format})
        writer.sheets[s_name].conditional_format("E1:G17", {'type': 'cell', 'criteria': '!=', 'value': "Dummy",'format': nodyn_format})
        writer.sheets[s_name].conditional_format("H1:J17", {'type': 'cell', 'criteria': '!=', 'value': "Dummy",'format': classic_format})